
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
       - id: bank-service
         uri: lb://BANK-SERVICE
         predicates:
           - Path=/api/bank/**
         filters:
           - AuthenticationFilter

       - id: user-service
         uri: lb://USER-SERVICE
         predicates:
           - Path=/api/user/**
         filters:
           - AuthenticationFilter


